server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080
